2013-03-28 10:28:14,908 - ERROR - stderr - Traceback (most recent call last): (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,909 - ERROR - stderr -   File "/Users/garetjax/.virtualenvs/simple-cloud/bin/scloud", line 8, in <module> (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,909 - ERROR - stderr -     load_entry_point('simple-cloud==0.1a', 'console_scripts', 'scloud')() (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,909 - ERROR - stderr -   File "/Users/garetjax/Projects/subcommands/subcommands/main.py", line 65, in _main (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,911 - ERROR - stderr -     sys.exit(main(name, package, sys.argv[1:])) (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,911 - ERROR - stderr -   File "/Users/garetjax/Projects/subcommands/subcommands/main.py", line 53, in main (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,911 - ERROR - stderr -     res = args.command.execute(args) (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,912 - ERROR - stderr -   File "/Users/garetjax/Projects/simple-cloud/simplecloud/commands/__init__.py", line 66, in execute (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,912 - ERROR - stderr -     self.process_vm(name, names[name], args) (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,912 - ERROR - stderr -   File "/Users/garetjax/Projects/simple-cloud/simplecloud/commands/__init__.py", line 84, in process_vm (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,912 - ERROR - stderr -     return self.handler(self, name, uuid, args) (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,912 - ERROR - stderr -   File "/Users/garetjax/Projects/simple-cloud/simplecloud/commands/manage.py", line 88, in shell_vm (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,912 - ERROR - stderr -     subprocess.check_call(cmd) (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,912 - ERROR - stderr -   File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 506, in check_call (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,913 - ERROR - stderr -     retcode = call(*popenargs, **kwargs) (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,913 - ERROR - stderr -   File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 493, in call (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,914 - ERROR - stderr -     return Popen(*popenargs, **kwargs).wait() (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,914 - ERROR - stderr -   File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1291, in wait (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,914 - ERROR - stderr -     pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0) (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,914 - ERROR - stderr -   File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,914 - ERROR - stderr -     return func(*args) (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
2013-03-28 10:28:14,915 - ERROR - stderr - KeyboardInterrupt (/Users/garetjax/Projects/subcommands/subcommands/logging.py:87)
